package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.SerializedName;

/**
 * Artist generated by hbm2java
 */
public class Artist  {

	@SerializedName("listArtists")
	private List<Artist> listArtists;
	
	@SerializedName("totalArtists")
	private String totalArtists;
	
	@SerializedName("id")
	private Integer id;
	
	@SerializedName("name")
	private String name;
	
	@SerializedName("realname")
	private String realname;
	
	@SerializedName("photo")
	private String photo;
	
	@SerializedName("introduction")
	private String introduction;
	
	@SerializedName("enabled")
	private boolean enabled;
	
	@SerializedName("nation")
	private String nation;
	
	@SerializedName("birthday")
	private String birthday;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	

	public String getTotalArtists() {
		return totalArtists;
	}

	public void setTotalArtists(String totalArtists) {
		this.totalArtists = totalArtists;
	}

	
	

	public List<Artist> getListArtists() {
		return listArtists;
	}

	public void setListArtists(List<Artist> listArtists) {
		this.listArtists = listArtists;
	}
	
	

	public Artist(List<Artist> listArtists, String totalArtists, Integer id, String name, String realname, String photo,
			String introduction, boolean enabled, String nation, String birthday) {
		super();
		this.listArtists = listArtists;
		this.totalArtists = totalArtists;
		this.id = id;
		this.name = name;
		this.realname = realname;
		this.photo = photo;
		this.introduction = introduction;
		this.enabled = enabled;
		this.nation = nation;
		this.birthday = birthday;
	}

	public Artist() {
		super();
	} 
	
	
	
}
