package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.SerializedName;

/**
 * Categories generated by hbm2java
 */
public class Categories{

	@SerializedName("id")
	private Integer id;
	
	@SerializedName("name")
	private String name;
	
	@SerializedName("introduction")
	private String introduction;
	
	@SerializedName("photo")
	private String photo;
	
	@SerializedName("enabled")
	private boolean enabled;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Categories(Integer id, String name, String introduction, String photo, boolean enabled) {
		super();
		this.id = id;
		this.name = name;
		this.introduction = introduction;
		this.photo = photo;
		this.enabled = enabled;
	}

	public Categories() {
		super();
	}
	
	
	
	
}
