package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import com.google.gson.annotations.SerializedName;

/**
 * Follow generated by hbm2java
 */
public class Follow{

	@SerializedName("id")
	private Integer id;	

}
