package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import com.google.gson.annotations.SerializedName;

/**
 * SongsArtists generated by hbm2java
 */
public class SongsArtists {

	@SerializedName("id")
	private Integer id;
	
	@SerializedName("artist")
	private Artist artist;
	
	@SerializedName("song")
	private Song song;

	



}
