package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.SerializedName;

/**
 * Song generated by hbm2java
 */
public class Song {

	@SerializedName("id")
	private Integer id;

	@SerializedName("name")
	private String name;

	@SerializedName("introduction")
	private String introduction;

	@SerializedName("createdTime")
	private Date createdTime;

	@SerializedName("updatedTime")
	private Date updatedTime;

	@SerializedName("photo")
	private String photo;

	@SerializedName("lyric")
	private String lyric;

	@SerializedName("url")
	private String  url;

	@SerializedName("enabled")
	private boolean enabled;
	
	@SerializedName("artistId")
	private int artistId;
	
	@SerializedName("categoryId")
	private int categoryId;

//	@SerializedName("songsArtistses")
//	private Set<SongsArtists> songsArtistses = new HashSet<SongsArtists>(0);

	private ArrayList<Artist> artist;

//	@SerializedName("gallerySongses")
//	private Set<GallerySongs> gallerySongses = new HashSet<GallerySongs>(0);

	private Gallery gallery;

	
	public Song(Integer id, String name, String introduction, Date createdTime, Date updatedTime, String photo,
		String lyric, String url, boolean enabled, int artistId, int categoryId, ArrayList<Artist> artist,
		Gallery gallery) {
	super();
	this.id = id;
	this.name = name;
	this.introduction = introduction;
	this.createdTime = createdTime;
	this.updatedTime = updatedTime;
	this.photo = photo;
	this.lyric = lyric;
	this.url = url;
	this.enabled = enabled;
	this.artistId = artistId;
	this.categoryId = categoryId;
	this.artist = artist;
	this.gallery = gallery;
}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getIntroduction() {
		return introduction;
	}


	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}


	public Date getCreatedTime() {
		return createdTime;
	}


	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}


	public Date getUpdatedTime() {
		return updatedTime;
	}


	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}


	public String getPhoto() {
		return photo;
	}


	public void setPhoto(String photo) {
		this.photo = photo;
	}


	public String getLyric() {
		return lyric;
	}


	public void setLyric(String lyric) {
		this.lyric = lyric;
	}


	public String getUrl() {
		return url;
	}


	public void setUrl(String url) {
		this.url = url;
	}


	public boolean isEnabled() {
		return enabled;
	}


	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}


	public int getArtistId() {
		return artistId;
	}


	public void setArtistId(int artistId) {
		this.artistId = artistId;
	}


	public int getCategoryId() {
		return categoryId;
	}


	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}


	public ArrayList<Artist> getArtist() {
		return artist;
	}


	public void setArtist(ArrayList<Artist> artist) {
		this.artist = artist;
	}


	public Gallery getGallery() {
		return gallery;
	}


	public void setGallery(Gallery gallery) {
		this.gallery = gallery;
	}


	public Song() {
		super();
	}

}
