package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

import com.google.gson.annotations.SerializedName;

/**
 * Users generated by hbm2java
 */
public class User {

	@SerializedName("id")
	private Integer id;
	
	@NotEmpty
	@Email
	@SerializedName("email")
	private String email;
	
	@NotEmpty
	@SerializedName("password")
	private String password;
	
	@NotEmpty
	@SerializedName("username")
	private String username;
	
	@SerializedName("enabled")
	private boolean enabled;
	
	@SerializedName("photos")
	private String photos;
	
	
	@SerializedName("verificationCode")
	private String verificationCode;
	
	
	@SerializedName("createdTime")
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date createdTime;
	
	public User() {
		super();
	}
	
	public User(Integer id, String email, String password, String username, boolean enabled, String photos,
			String verificationCode, Date createdTime) {
		super();
		this.id = id;
		this.email = email;
		this.password = password;
		this.username = username;
		this.enabled = enabled;
		this.photos = photos;
		this.verificationCode = verificationCode;
		this.createdTime = createdTime;
	}

	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getPhotos() {
		return photos;
	}

	public void setPhotos(String photos) {
		this.photos = photos;
	}

	public String getVerificationCode() {
		return verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	
	
	

}
