package com.demo.entity;
// Generated Jan 12, 2022, 7:27:30 AM by Hibernate Tools 5.1.10.Final

/**
 * UsersRoles generated by hbm2java
 */
public class UsersRoles implements java.io.Serializable {

	private Integer id;
	private Roles roles;
	private User users;

	public UsersRoles() {
	}

	public UsersRoles(Roles roles, User users) {
		this.roles = roles;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

}
